### ISSUE TITLE
Documentation layout and examples.

### ISSUE THREAD

**Issue by baluyotraf** [sqlalchemy/mako#369]
Hello!

I'm checking the link in the `README.md` which is `https://docs.makotemplates.org/en/latest/usage.html`. It looks like the API Reference side bar overflows.

![image](https://user-images.githubusercontent.com/7478783/204676352-8f29ffb5-7e43-40f9-96fe-828a603de179.png)

Another thing is the code in the usage does not work for Python3.

![image](https://user-images.githubusercontent.com/7478783/204676642-d6830faf-0f78-4ffb-bfa3-8dbcac1a5ea2.png)

There is already a discussion in https://github.com/sqlalchemy/mako/issues/234 about fixing it, basically changing `StringIO` to `io`

I can take a look at these issues, but I want to make sure that I didn't miss something.

**Comment by zzzeek** [comment]
these are going to be a little mroe difficult than usual to fix since you'd need to fix them over in Mako's sphinx extension at https://github.com/sqlalchemyorg/zzzeeksphinx/ .    For some indication of what changed in general see https://github.com/sqlalchemy/alembic/commit/edd64ea2a322049a4a536c1a9ae8e498db73be23 and https://github.com/sphinx-doc/sphinx/issues/11000

**Comment by baluyotraf** [comment]
Okay, but the example should be fixed here right? Since it's part of the content.

Looking at the alembic solution, I assume you prefer to adjust the width?

**Comment by zzzeek** [comment]
oh there's an import in there too, sure that should be fixed as well, thanks!

**Comment by zzzeek** [comment]
for the CSS it's a small width adjust and also an "overflow:auto" so that it can scroll.

**Comment by zzzeek** [comment]
this is fixed
